Support the application of Conan's BuildEnv/RunEnv
afri-bit/vsconan pull request #44
Opened 2024-08-12 10:08 UTC by hackenbergstefan

Closes #36

2024-08-13 21:21 UTC, afri-bit commented on resources/print_env.py
@hackenbergstefan I assume this is the conan file to activate the conan environment and retrieve all the environment variables, right?

2024-08-13 21:56 UTC, afri-bit commented on resources/print_env.py
@hackenbergstefan I guess we can use a file watcher that watch the installation folder, where the file `conanbuildenv.sh` or `conanrunenv.sh` are stored and used to set the variable 😸 With this we have a neutral environment, since the conan python api in version 1 and 2 are different.

2024-08-14 08:30 UTC, hackenbergstefan commented on resources/print_env.py
> @hackenbergstefan I assume this is the conan file to activate the conan environment and retrieve all the environment variables, right?

Yes, this is a small script that aggregates the environment variables. I've tried to manage using conan cmdline calls only, but that doesn't work.

Moreover, I've forgot to mention and document that it is working for conan 2 (currently) only. Conan 1 API is more complex... I have to investigate...

2024-08-14 08:35 UTC, hackenbergstefan commented on resources/print_env.py
> @hackenbergstefan I guess we can use a file watcher that watch the installation folder, where the file `conanbuildenv.sh` or `conanrunenv.sh` are stored and used to set the variable 😸 With this we have a neutral environment, since the conan python api in version 1 and 2 are different. What do you think?

Not sure I understood your suggestion... ^^
`conanbuildenv.sh` and `conanrunenv.sh` are both generated by Conan with every `install` cmd. The user has to decide whether to use BuildEnv or RunEnv.

2024-08-20 20:53 UTC, afri-bit requested changes
There are some minority changes, but overall looks good :) after that we can merge the pull request

2024-08-20 20:53 UTC, afri-bit commented on test/conan/readEnv.test.ts
> +    }
You need to mock the `vscode.window.showErrorMessage()` otherwise the test will not run, due to mocked `vscode` module

2024-08-20 20:53 UTC, afri-bit commented on test/conan/readEnv.test.ts
I think for testing we need to mention that it is necessary to install the python with conan version 2.x.x within a virtual environment

2024-08-22 08:44 UTC, hackenbergstefan commented on test/conan/readEnv.test.ts
Added a paragraph to CONTRIBUTING.md

2024-08-22 08:44 UTC, hackenbergstefan commented
Sorry for the whitespace changes 🙈 
I (hopefully) reverted all of them.

2024-08-22 21:48 UTC, afri-bit commented on test/conan/readEnv.test.ts
> +    }
or maybe it was because the python was not found in my system 🤔

2024-08-22 21:55 UTC, afri-bit approved these changes

2024-08-22 21:56 UTC, merged

2024-08-25 11:31 UTC, hackenbergstefan commented
Thanks for merging! :-)